# Test Workflow to test custom actions
name: TestActions


run-name: "[${{github.event_name}}] ${{github.workflow}} on ${{github.ref_name}} (${{github.sha}})"


on:
  push:

jobs:
  test:
    name: test-${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-24.04-arm, windows-2025, windows-2022, windows-11-arm, macos-15-intel, macos-26]
    steps:
      - uses: actions/checkout@v6
        name: Clone repository
        with:
          submodules: true

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@v11.5

      # Setup vcpkg: ensures vcpkg is downloaded and built.
      # Since vcpkg.json is being used later on to install the packages
      # when `run-cmake` runs, no packages are installed at this time
      # (and vcpkg does not run).
      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch.
        #with:
          # This is the default location of the directory containing vcpkg sources.
          # Change it to the right location if needed.
          # vcpkgDirectory: '${{ github.workspace }}/vcpkg'

          # If not using a Git submodule for vcpkg sources, this input
          # specifies which commit id to checkout from a Git repo.
          # Notes:
          # - it must _not_ be set if using a Git submodule for vcpkg.
          # - if not provided, the `vcpkgConfigurationJsonGlob` or `vcpkgJsonGlob`
          #   are being used to locate either a vcpkg-configuration.json or vcpkg.json
          #   in order to use the builtin-baseline or the default-registry's
          #   builtin baseline.
          # vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'

          # This is only needed if the command `vcpkg install` must run at this step.
          # Instead it is highly suggested to let `run-cmake` to run vcpkg later on
          # using the vcpkg.cmake toolchain. The default is `false`.
           runVcpkgInstall: true

          # This is only needed if `runVpkgInstall` is `true`.
          # This glob expression used to locate the vcpkg.json and  use
          # its directory location as `working directory` when running `vcpkg install`.
          # Change it to match a single manifest file you want to use.
          # Note: do not use `${{ github.context }}` to compose the value as it
          # contains backslashes that would be misinterpreted. Instead
          # compose a value relative to the root of the repository using
          # `**/path/from/root/of/repo/to/vcpkg.json` to match the desired `vcpkg.json`.
          # vcpkgJsonGlob: '**/vcpkg.json'
